#!/bin/bash
#PBS -l select=1:ncpus=10:ngpus=1
#PBS -P CSCI1214
#PBS -q gpu_1
#PBS -l walltime=1:00:00
#PBS -o /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc_results/omp_bts_8.out
#PBS -e /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc_results/omp_bts_8.err
#PBS -m abe
#PBS -M 17650739@sun.ac.za
#PBS -N sbta_8

ulimit -s unlimited
source /etc/profile.d/modules.sh

cd /mnt/lustre/users/tebrahim/SUN-EM-CMOM/omp_build

export OMP_NUM_THREADS=8
time ./mom ../examples/a/bow_tie_array_small.mom --dgfm

