#!/bin/bash
#PBS -l select=6:ncpus=24:mpiprocs=8:nodetype=haswell_reg
#PBS -P CSCI1214
#PBS -q normal
#PBS -l walltime=1:00:00
#PBS -o /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/results/ompi/bt1k_48p_3t.out
#PBS -e /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/results/ompi/bt1k_48p_3t.err
#PBS -m abe
#PBS -M 17650739@sun.ac.za
#PBS -N bt1k_48p_3t

ulimit -s unlimited

nproc= cat $PBS_NODEFILE | wc -l


cd /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/ompi_build

time /apps/compilers/pgi/linux86-64/19.4/mpi/openmpi-3.1.3/bin/mpiexec -np 48 -machinefile $PBS_NODEFILE -x OMP_NUM_THREADS=3 mom_mpi ../../examples/bow_tie_array/bow_tie_array_med.mom --dgfm