#!/bin/bash 
#PBS -l select=2:ncpus=24:mpiprocs=1:nodetype=haswell_reg
#PBS -P CSCI1214
#PBS -q normal
#PBS -l walltime=10:00:00
#PBS -o /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/results/feko_test/sfbt8_2p.out
#PBS -e /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/results/feko_test/sfbt8_2p.err
#PBS -m abe
#PBS -M 17650739@sun.ac.za
#PBS -N sfbt8_2p


# FEKO PATH
PATH_TO_FEKO=/apps/chpc/compmech/altair/feko2018.2/altair/feko/
export FEKOJOBDIR=/mnt/lustre/users/tebrahim/SUN-EM-CMOM/examples/bow_tie_array/
# FEKO_TMPDIR
export FEKO_TMPDIR=./tmp

cd $FEKOJOBDIR
# additional setup
ulimit -s unlimited
ulimit -n 2400
ulimit -a

export ALTAIR_LICENSE_PATH=6200@chpcviz1
export FEKO_CSV_RESOURCE_REPORTING_PRESET=use_envvars
. $PATH_TO_FEKO/bin/initfeko
export FEKO_WHICH_MPI=11

runfeko bow_tie_array_small.pre --use-job-scheduler