#!/bin/bash
#PBS -l select=1:ncpus=24:mpi_procs=24:nodetype=haswell_reg
#PBS -P CSCI1214
#PBS -q normal
#PBS -l walltime=5:00:00
#PBS -o /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/results/mpi/lbta_24.out
#PBS -e /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/results/mpi/lbta_24.err
#PBS -m abe
#PBS -M 17650739@sun.ac.za
#PBS -N mpi_bow_tie_19000

ulimit -s unlimited

nproc = cat $PBS_NODEFILE | wc -l


cd /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/mpi_build

time mpiexec -np 24 -machinefile $PBS_NODEFILE mom_mpi ../../examples/bow_tie_array/bow_tie_array_small.mom --dgfm
