#!/bin/bash
#PBS -l select=2:ncpus=24:mpiprocs=24:nodetype=haswell_reg
#PBS -P CSCI1214
#PBS -q normal
#PBS -l walltime=1:00:00
#PBS -o /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/results/mpi/lbta_12.out
#PBS -e /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/results/mpi/lbta_12.err
#PBS -m abe
#PBS -M 17650739@sun.ac.za
#PBS -N mpi_bow_tie_12

ulimit -s unlimited

nproc= cat $PBS_NODEFILE | wc -l


cd /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/mpi_build

time /apps/compilers/pgi/linux86-64/19.4/mpi/openmpi-3.1.3/bin/mpiexec -np 12 -machinefile $PBS_NODEFILE mom_mpi ../../examples/bow_tie_array/bow_tie_array_small.mom --dgfm

