#!/bin/bash
#PBS -l select=1:ncpus=10:ngpus=1
#PBS -P CSCI1214
#PBS -q gpu_1
#PBS -l walltime=1:00:00
#PBS -o /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc.out
#PBS -e /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc.err
#PBS -m abe
#PBS -M 17650739@sun.ac.za

ulimit -s unlimited
source /etc/profile.d/modules.sh

export LM_LICENSE_FILE=/apps/compilers/pgi/linux86-64/2019/license.dat
module add chpc/pgi/19.4
module add blas/gcc/64/3.6.0
module add lapack/gcc/64/3.6.0
module add chpc/cmake/3.11.0/gcc-6.1.0

cd /mnt/lustre/users/tebrahim/SUN-EM-CMOM/build

cmake -DCHPC=ON -DCOMP=ON -DCMAKE_C_COMPILER="/apps/compilers/pgi/linux86-64/19.4/bin/pgcc" -DCMAKE_CXX_COMPILER="/apps/compilers/pgi/linux86-64/19.4/bin/pgc++" ..
make
