#!/bin/bash
#PBS -l select=8:ncpus=24:mpiprocs=1:nodetype=haswell_reg
#PBS -P CSCI1214
#PBS -q normal
#PBS -l walltime=03:00:00
#PBS -o /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/results/final/50/bta50_8p_24t.out
#PBS -e /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/results/final/50/bta50_8p_24t.err
#PBS -m abe
#PBS -M 17650739@sun.ac.za
#PBS -N bta50_8p_24t

ulimit -s unlimited

nproc= cat $PBS_NODEFILE | wc -l


cd /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/ompi_build

time /apps/compilers/pgi/linux86-64/19.4/mpi/openmpi-3.1.3/bin/mpiexec -np 8 -machinefile $PBS_NODEFILE -x OMP_NUM_THREADS=24 mom_mpi ../../examples/bow_tie_array/bow_tie_array_50.mom --dgfm
