#!/bin/bash
#PBS -l select=1:ncpus=8:mpiprocs=8:nodetype=haswell_reg
#PBS -P CSCI1214
#PBS -q serial
#PBS -l walltime=10:00:00
#PBS -o /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/results/mpiVomp/8p.out
#PBS -e /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/results/mpiVomp/8p.err
#PBS -m abe
#PBS -M 17650739@sun.ac.za
#PBS -N 8p

ulimit -s unlimited

nproc= cat $PBS_NODEFILE | wc -l

cd /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/mpi_build

time /apps/compilers/pgi/linux86-64/19.4/mpi/openmpi-3.1.3/bin/mpiexec -np 8 -machinefile $PBS_NODEFILE mom_mpi ../../examples/bow_tie_array/bow_tie_array_small.mom --dgfm
