#!/bin/bash
#PBS -l select=2:ncpus=24:mpiprocs=24:nodetype=haswell_reg
#PBS -P CSCI1214
#PBS -q normal
#PBS -l walltime=1:00:00
#PBS -o /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/results/profile.out
#PBS -e /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/results/profile.err
#PBS -m abe
#PBS -M 17650739@sun.ac.za
#PBS -N profile

ulimit -s unlimited

nproc= cat $PBS_NODEFILE | wc -l


cd /mnt/lustre/users/tebrahim/SUN-EM-CMOM/chpc/mpi_build

lscpu
